on:
  - pull_request

permissions:
  contents: write

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 7

      - uses: actions/checkout@v3
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
l
      - name: Install dependencies
        run: pnpm install

      - name: All lining
        run: pnpm lint

      - name: Webapp Build
        run: pnpm webapp build

      - name: Webapp Tests
        run: pnpm webapp ci

      - name: Design System Build & Tests
        run: pnpm design ci

      - name: Design System Development Smoke Test
        run: pnpm design dev --smoke-test
