on:
  - pull_request

permissions:
  contents: write

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 7

      - uses: actions/checkout@v3
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install

      # - name: Install Playwright
        # run: pnpm dlx playwright install

      - name: Run linter
        run: pnpm lint

      - name: Build Webapp
        run: pnpm webapp build

      - name: Run webapp tests
        run: pnpm webapp ci

      - name: Run & Test Design System
        run: pnpm design ci
